#pragma once
#include <stdint.h>

#define MUSE_AVATAR_WIDTH 240
#define MUSE_AVATAR_HEIGHT 240
#define MUSE_AVATAR_FRAMES 20
#define MUSE_AVATAR_FRAME_BYTES (MUSE_AVATAR_WIDTH * MUSE_AVATAR_HEIGHT * 2)
#define MUSE_AVATAR_COMPACT_WIDTH 100
#define MUSE_AVATAR_COMPACT_HEIGHT 100
#define MUSE_AVATAR_COMPACT_BYTES (MUSE_AVATAR_COMPACT_WIDTH * MUSE_AVATAR_COMPACT_HEIGHT * 2)
#define MUSE_AVATAR_RECORD_WIDTH 164
#define MUSE_AVATAR_RECORD_HEIGHT 164
#define MUSE_AVATAR_RECORD_BYTES (MUSE_AVATAR_RECORD_WIDTH * MUSE_AVATAR_RECORD_HEIGHT * 2)
#define MUSE_AVATAR_BYTES (MUSE_AVATAR_FRAMES * MUSE_AVATAR_FRAME_BYTES + MUSE_AVATAR_COMPACT_BYTES + MUSE_AVATAR_RECORD_BYTES)

/* The firmware returns a pointer to Flash; the host simulator loads the same bytes. */
const uint8_t *muse_avatar_data(void);
